### ISSUE TITLE
[Bug] This project does not play well with CSP

### ISSUE THREAD

**Issue by stoic-hugo** [benvinegar/counterscale#101]
Hi! Very nice project you have here!

I added the CF Pages URL with the tracker JS to the `script` in content security policy, but then other elements also get blocked, like some inline images and styles. I would have to disable my CSP entirely to get this project to work. (Also had to set `unsafe-inline` due to the inline items)

**Comment by benvinegar** [comment]
Hey @ka259 – thanks for highlighting this.

I haven't verified yet, but I'll take your word for it because I'd hadn't accounted for CSP at any point during this project (super ambarrassing, especially given I [once gave a talk on CSP](http://benvinegar.github.io/csp-talk-2013/#1)).

Will definitely be prioritizing.
