### ISSUE TITLE
Table card row fill rendering incorrectly on Safari

### ISSUE THREAD

**Issue by benvinegar** [benvinegar/counterscale#44]
<img width="642" alt="image" src="https://github.com/benvinegar/counterscale/assets/2153/2f8ffd57-8708-4643-918f-64fdfbb7818a">

**Comment by benvinegar** [comment]
This is apparently an old WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=34392

**Comment by anurag-roy** [comment]
@benvinegar yep that's what I found too - the background is being applied to each td element rather than their containing tr.

Changing the `display` on the td to `block` or `flex` seems to solve that, but is causing other issues like the row not occupying 100% of the width.

I'm still giving it a shot and seeing if anything works!

**Comment by benvinegar** [comment]
I was thinking of just abandoning trying to apply the gardient to the row and instead apply it to the first `td` alone, which should work in all browsers. It just will mean the bars won't look as "full", which is probably okay.

**Comment by anurag-roy** [comment]
Yes that works too, if not better. I can give it a shot, if that's fine.

**Comment by benvinegar** [comment]
Closed by #46
